-- the data used within this folder is exported from the database in database-admin. refer to data-base admin for original source code.
-- the only exception is lookups-exercises, which uses a dataset made (painfully) by hand.
